---
hostname: ajh-fat
ubuntu_codename: xenial
jobserver: true
mount_path: /data
distribution_path: /data/aijihui
application_path: "{{ distribution_path }}/aijihui-web-2"

ajh_pem_private_path: /data/bica
ajh_pem_public_path: /data/bica