---
- name: add PHP repository from PPA
  apt_repository:
    repo: ppa:ondrej/php
    update_cache: true

- name: install php
  raw: sudo apt-get install -y php8.3
  register: result

- name: remove apache2
  apt:
    name: apache2
    state: absent

- name: install Mbstring PHP Extension
  apt:
    name: php{{ php_version }}-mbstring

- name: install XML PHP Extension
  apt:
    name: php{{ php_version }}-xml

- name: install MySQL PHP Extension
  apt:
    name: php{{ php_version }}-mysql

- name: install Zip PHP Extension
  apt:
    name: php{{ php_version }}-zip

- name: install cURL PHP Extension
  apt:
    name: php{{ php_version }}-curl

- import_tasks: php-fpm.yml
