---
- name: create a new partition for the data disk
  parted:
    device: /dev/vdb
    number: 1
    state: present

- name: create a file system for the data disk
  filesystem:
    dev: /dev/vdb1
    fstype: ext4

- name: mount the data disk
  mount:
    path: "{{ mount_path }}"
    src: /dev/vdb1
    fstype: ext4
    state: present
