---
- name: add GPG key for nodejs repository
  apt_key:
    url: http://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: add nodejs 7.x repository from official source
  apt_repository:
    repo: deb https://deb.nodesource.com/node_7.x {{ ubuntu_codename }} main
    update_cache: true

- name: install nodejs
  apt:
    name: nodejs

- name: install gulp cli globally
  npm:
    name: gulp-cli
    global: true
