---
- name: add GPG key for nginx repository
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key

#- name: add nginx stable repository from official source
#  apt_repository:
#    repo: deb http://nginx.org/packages/ubuntu/ {{ ubuntu_codename }} nginx
#    update_cache: true

- name: install nginx
  apt:
    name: nginx

- name: setup nginx http config file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    backup: true
  register: nginx_http_config

- name: remove nginx default server config file
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: ensure nginx service
  service:
    name: nginx
    state: started
    enabled: true

- name: reload nginx service if config file changed
  service:
    name: nginx
    state: reloaded
  when: nginx_http_config.changed
